from sqlalchemy import Select, func, Update, and_

from efficieno.components.view_actions import Action
from efficieno.components.view_metrics import Metric
from efficieno.components.view_tables import ViewTable
from efficieno.components.views import View
from efficieno.components.charts import ChartObject
from thermax_planmax.data_objects.customers import Customers
from thermax_planmax.data_objects.planmax_headers import PlanMaxHeaders
from thermax_planmax.data_objects.calender import Calender
from thermax_planmax.data_objects.organizations import Organizations
from thermax_planmax.data_objects.di_details import DIDetails  # noqa: F401
from thermax_planmax.data_objects.model_xref import ModelXref  # noqa: F401
from thermax_planmax.data_objects.operating_units import OperatingUnits  # noqa: F401
from thermax_planmax.data_objects.order_headers import OrderHeaders  # noqa: F401
from thermax_planmax.data_objects.order_lines import OrderLines  # noqa: F401
from thermax_planmax.data_objects.order_types import OrderTypes  # noqa: F401
from thermax_planmax.data_objects.planmax_lines import PlanMaxLines  # noqa: F401
from thermax_planmax.data_objects.prn_details import PRNDetails  # noqa: F401
from thermax_planmax.data_objects.tech_ocl_master import TechOCLMaster  # noqa: F401
from thermax_planmax.data_objects.tech_ocl_lines import TechOCLLines  # noqa: F401

class MasterPlanHeaders(View):
    query = Select(
        PlanMaxHeaders,
        Customers,
        Calender,
        Organizations
    ).outerjoin(PlanMaxHeaders.customers).outerjoin(PlanMaxHeaders.calender).outerjoin(PlanMaxHeaders.organizations)

    all_cols_master_plan_headers_v = ViewTable(
        display_name="Master Plan (All Cols)",
        table_header="Master Plan (All Cols)",
        table_description="Master Plan (All Cols)",
        query=query.with_only_columns(
            PlanMaxHeaders.curr_thx_commitment_date,
            PlanMaxHeaders.project_number,
            PlanMaxHeaders.sales_order_number,
            PlanMaxHeaders.model_line_number,
            Customers.party_name,
            PlanMaxHeaders.operating_unit_id,
            Organizations.organization_code,
            PlanMaxHeaders.sales_order_header_id,
            PlanMaxHeaders.sales_order_number,
            PlanMaxHeaders.model_line_id,
            PlanMaxHeaders.model_line_number,
            PlanMaxHeaders.order_type_id,
            PlanMaxHeaders.group_name,
            PlanMaxHeaders.sub_group,
            PlanMaxHeaders.product_category,
            PlanMaxHeaders.prn_applicable,
            PlanMaxHeaders.inspection_required,
            PlanMaxHeaders.project_id,
            PlanMaxHeaders.project_number,
            PlanMaxHeaders.std_nstd,
            PlanMaxHeaders.sos_item,
            PlanMaxHeaders.mfg_organization_id,
            PlanMaxHeaders.orig_cust_required_date,
            PlanMaxHeaders.curr_cust_required_date,
            PlanMaxHeaders.orig_thx_commitment_date,
            PlanMaxHeaders.curr_thx_commitment_date,
            PlanMaxHeaders.ho_order_commited_to,
            PlanMaxHeaders.ho_order_so_header,
            PlanMaxHeaders.ho_order_so_line,
            PlanMaxHeaders.oc_no,
            PlanMaxHeaders.oc_date,
            PlanMaxHeaders.tech_clarity_date,
            PlanMaxHeaders.engg_commt_dt,
            PlanMaxHeaders.oc_status,
            PlanMaxHeaders.oc_closure_date,
            PlanMaxHeaders.planned_invoice_dates,
            PlanMaxHeaders.planned_invoice_value,
            PlanMaxHeaders.wip_folder_release_date,
            PlanMaxHeaders.commissioning_date,
            PlanMaxHeaders.site_release_date,
            PlanMaxHeaders.planner,
            PlanMaxHeaders.tca,
            PlanMaxHeaders.send_email,
            PlanMaxHeaders.fg_month_change_remarks,
            PlanMaxHeaders.shell_boiler_appr_auth,
            PlanMaxHeaders.reason_for_otp,
            PlanMaxHeaders.order_status,
            PlanMaxHeaders.interface_status,
            PlanMaxHeaders.creation_date,
            PlanMaxHeaders.last_update_date,
            PlanMaxHeaders.refresh_date,
            PlanMaxHeaders.bill_site_use_id,
            PlanMaxHeaders.bill_cust_acct_site_id,
            PlanMaxHeaders.bill_party_site_id,
            PlanMaxHeaders.bill_party_id,
            PlanMaxHeaders.bill_location_id,
            PlanMaxHeaders.ship_site_use_id,
            PlanMaxHeaders.ship_cust_acct_site_id,
            PlanMaxHeaders.ship_party_site_id,
            PlanMaxHeaders.ship_party_id,
            PlanMaxHeaders.ship_location_id,
            PlanMaxHeaders.order_intake_status,
            PlanMaxHeaders.bom_common_status,
            PlanMaxHeaders.reflection_config_status,
            PlanMaxHeaders.mat_planning_status,
            PlanMaxHeaders.sourcing_status,
            PlanMaxHeaders.commit_dates_status_mfg,
            PlanMaxHeaders.commit_dates_status_mat,
            PlanMaxHeaders.mfg_job_folder_status,
            PlanMaxHeaders.prn_status,
            PlanMaxHeaders.eol_mat_avail_status,
            PlanMaxHeaders.wip_pur_mat_status,
            PlanMaxHeaders.project_segment1,
            PlanMaxHeaders.project_description,
            PlanMaxHeaders.project_task_number,
            PlanMaxHeaders.project_task_id,
            PlanMaxHeaders.project_task_description,
            PlanMaxHeaders.operating_unit_name,
            PlanMaxHeaders.region_of_order,
            PlanMaxHeaders.type_of_order,
            PlanMaxHeaders.hdr_order_type,
            PlanMaxHeaders.hdr_booked_date,
            PlanMaxHeaders.otm_tech_ocl_no,
            PlanMaxHeaders.fuel,
            PlanMaxHeaders.pressure,
            PlanMaxHeaders.special_instructions,
            PlanMaxHeaders.product_model,
            PlanMaxHeaders.ordered_date,
            PlanMaxHeaders.order_currency,
            PlanMaxHeaders.total_unit_value,
            PlanMaxHeaders.conversion_rate,
            PlanMaxHeaders.total_unit_value_in_inr,
            PlanMaxHeaders.prn_customer_dely_date,
            PlanMaxHeaders.prn_revised_dely_reqd_date,
            PlanMaxHeaders.prn_number,
            PlanMaxHeaders.prn_approved_date,
            PlanMaxHeaders.freight_pay,
            PlanMaxHeaders.inco_terms,
            PlanMaxHeaders.abp_percent,
            PlanMaxHeaders.pgb_percent,
            PlanMaxHeaders.bonus,
            PlanMaxHeaders.ld_applicable,
            PlanMaxHeaders.penalty,
            PlanMaxHeaders.insurance_by,
            PlanMaxHeaders.sales_engineer,
            PlanMaxHeaders.otm_header_id,
            PlanMaxHeaders.project_task_name,
            PlanMaxHeaders.proj_specific_llbom,
            PlanMaxHeaders.llbom_release_date,
            PlanMaxHeaders.llbom_pr,
            PlanMaxHeaders.di_number,
            PlanMaxHeaders.di_date,
            PlanMaxHeaders.di_value,
            PlanMaxHeaders.di_freight,
            PlanMaxHeaders.di_recommended_transporter,
            PlanMaxHeaders.di_transportation_scope,
            PlanMaxHeaders.last_invoice_no,
            PlanMaxHeaders.last_invoice_date,
            PlanMaxHeaders.invoiced_value,
            PlanMaxHeaders.contractual_plan_otp,
            PlanMaxHeaders.delivery_otp,
            PlanMaxHeaders.original_project_no,
            PlanMaxHeaders.rated_standard_man_hrs,
            PlanMaxHeaders.mfg_commitment_date,
            PlanMaxHeaders.plan_eol_mech_date,
            PlanMaxHeaders.plan_eol_ei_date,
            PlanMaxHeaders.folder_status,
            PlanMaxHeaders.regional_commercial,
            PlanMaxHeaders.actual_fg_date,
            PlanMaxHeaders.shop_subcontract,
            PlanMaxHeaders.oc_required,
            PlanMaxHeaders.suggested_plan_date,
            PlanMaxHeaders.line_attribute9,
            PlanMaxHeaders.sos_en1_revision,
            PlanMaxHeaders.sos_mfg_revision,
            PlanMaxHeaders.sos_revision_date
        ),
        column_properties={},
        actions=[],
        inline_actions=None,
    )

    count_master_plan_headers = Metric(
        display_name="Master Plan",
        metric_description="Total Open Orders",
        query=func.count(PlanMaxHeaders.sales_order_number).label("Orders Count"),
        base_object=all_cols_master_plan_headers_v,
    )
